# Generated by Django 4.1.5 on 2023-01-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0003_familiar_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_animal', models.CharField(max_length=60)),
                ('reino', models.CharField(max_length=60)),
                ('clase', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_la_mascota', models.CharField(max_length=60)),
                ('tipo_de_mascota', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Dummy',
        ),
        migrations.RemoveField(
            model_name='familiar',
            name='fecha_nacimiento',
        ),
    ]
